report_state:
  name: Sends a ChangeReport to the Alexa Gateway
  fields:
    entity_id:
      required: True
      example: "sensor.garage_door"
    state:
      required: True
      example: "DETECTED"
process_request:
  name: Process an Alexa SmartHome request
