report_state:
  name: Sends a ChangeReport message to the Alexa Gateway
  fields:
    entity_id:
      required: True
      example: "sensor.garage_door"
process_request:
  name: Process a SmartHome request from Alexa
